---
- name: AWS role
  ansible.builtin.import_role:
    name: inqwise.common.aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 60
    tags_facts:
      private_dns: "private_dns"
      consul_cluster: "consul_cluster"
      advertised_listener: "kafka_advertised_listener"
      quorum_voters: "kafka_controller_quorum_voters"
      node_id: "kafka_node_id"
      snapshot: "data_snapshot"
      disk_delete_on_termination: "disk_delete_on_termination"

- name: Java role
  ansible.builtin.import_role:
    name: inqwise.common.java

- name: Kafka role
  ansible.builtin.import_role:
    name: inqwise.stacktrek.kafka
        
- name: Shrink logs role
  ansible.builtin.include_role:
    name: shrink_logs
    apply:
      tags: installation
  tags: installation

- name: Install Alloy
  ansible.builtin.include_role:
    name: alloy
  tags: always
  vars:
    alloy_user_groups:
      - systemd-journal
    env_file_vars:
      CUSTOM_ARGS: "--server.http.listen-addr=0.0.0.0:12345 --disable-reporting=true --stability.level=public-preview"
    config: |
      loki.write "local" {
        endpoint {
          url = "{{ loki_base_url }}/loki/api/v1/push"
        }
      }

      loki.relabel "journal" {
        forward_to = []

        rule {
          source_labels = ["__journal__systemd_unit"]
          regex         = "(kafka.service|telegraf.service)"
          action        = "keep"
        }
        rule {
          source_labels = ["__journal__systemd_unit"]
          target_label  = "unit"
        }
        rule {
          source_labels = ["__journal__hostname"]
          target_label  = "instance"
        }
      }

      loki.source.journal "read" {
        forward_to = [
          loki.write.local.receiver,
        ]
        relabel_rules = loki.relabel.journal.rules
        labels = {
          "job" = "integrations/node_exporter",
          "app" = "kafka",
        }
      }
