---
- name: AWS role
  ansible.builtin.import_role:
    name: inqwise.common.aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 60
    tags_facts:
      private_dns: "private_dns"
      consul_cluster: "consul_cluster"
      advertised_listener: "kafka_advertised_listener"
      quorum_voters: "kafka_controller_quorum_voters"
      node_id: "kafka_node_id"
      data_snapshot: "data_snapshot"

- name: Java role
  ansible.builtin.import_role:
    name: inqwise.common.java

- name: Kafka role
  ansible.builtin.import_role:
    name: inqwise.stacktrek.kafka
        
- name: Shrink logs role
  ansible.builtin.include_role:
    name: shrink_logs
    apply:
      tags: installation
  tags: installation